workflows:
  build_apk:
    name: Build Android Release APK
    max_build_duration: 120

    scripts:
      - name: Prepare Gradle
        script: |
          chmod +x ./gradlew

      - name: Build release APK
        script: |
          ./gradlew clean assembleRelease --no-daemon

    artifacts:
      - app/build/outputs/**/*.apk
